### ISSUE TITLE
Preprocessor directives are not recognized

### ISSUE THREAD

**Issue by SSaulenas** [BalticAmadeus/OpenedgeAblFormatter#156]
Example of include file:

```progress
&if '{&name}' = '' &then
    &scoped-define name ttTable
&endif

define {&visibility} temp-table {&name} no-undo
  field something as int
  field something2 as char
  index something as primary unique something
.
```

![image](https://github.com/user-attachments/assets/a0b0d4be-d743-4549-ada7-cd5bea2ba1fb)

**Comment by eglekaz** [comment]
Registered: https://github.com/usagi-coffee/tree-sitter-abl/issues/88

**Comment by PauliusKu** [comment]
I moved the example from this ticket to https://github.com/BalticAmadeus/AblFormatter/issues/217 as it's basically the same.
