### ISSUE TITLE
NO-LOCK not being parsed

### ISSUE THREAD

**Issue by gustason** [BalticAmadeus/OpenedgeAblFormatter#205]
For example,
``` abl
for each vacation no-lock vacation.id > 100:

end.
```
throws errors:
![image](https://github.com/user-attachments/assets/a00f09d6-b6fa-4f84-a72e-60074269a120)

**Comment by eglekaz** [comment]
The syntax in the example is not correct.
Should be:
```
for each vacation no-lock where vacation.id > 100:

end.
```
With this syntax everything seems okay.
If that is correct, then please close the issue.

**Comment by PauliusKu** [comment]
Closing it
